### ISSUE TITLE
Bug: rp2/RPI_PICO2 does not build

### ISSUE THREAD

**Issue by hmaerki** [mattytrentini/mpbuild#27] opened 2024-09-06 19:06 UTC
## Bug 1

The Raspberry Pi Pico RP2350 source is here:
https://github.com/dpgeorge/micropython/tree/rp2-add-rp2350/ports/rp2/boards/RPI_PICO2

However, the build fails.

## Bug 2

mpbuild uses container `micropython/build-micropython-arm` (See https://github.com/mattytrentini/mpbuild/blob/main/src/mpbuild/build.py#L7).

Where is the source (Dockerfile) of this container?

## Rationale

It could be helpful for Damien to have regression tests running on octoprobe.
For this, we have to fix above bugs.

If desired, I could
* Create a Dockerfile so we can supersed `micropython/build-micropython-arm`.
* Enhance the Dockerfile for builds for RP2350 builds (ARM and Risc-V)

**Comment by mattytrentini** [comment] 2024-09-07 00:08
`micropython/build-micropython-arm:latest` is built with Debian Bullseye which uses `arm-none-eabi-gcc` v8.5. I build [this container](https://hub.docker.com/r/micropython/build-micropython-arm) manually and publish them periodically, the [source is here](https://github.com/mattytrentini/build-micropython-arm-docker/).

The version of the pico-sdk that is currently used [requires a GCC version of >9.1](https://github.com/raspberrypi/pico-sdk/issues/1788). That issue is the cause of the failed build.

RPi have addressed the issue but a new release hasn't yet been published.

I've also published an updated version of `micropython/build-micropython-arm` that is built with Debian Bookwork and uses `arm-none-eabi-gcc` v12.2. It can be used by picking up the [bookworm tag](https://hub.docker.com/r/micropython/build-micropython-arm/tags) (ie `micropython/build-micropython-arm:bookworm`). The source is on the [update-to-bookworm](https://github.com/mattytrentini/build-micropython-arm-docker/tree/update_to_bookworm) branch.

You can build `RPI_PICO2` using the bookworm container with the `build-container` option:

```bash
mpbuild build RPI_PICO2 --build-container micropython/build-micropython-arm:bookworm
```

Eventually I'd like to use `bookworm` as the default build container but I haven't tried it on enough other builds yet to be confident in updating the version of gcc.

**Comment by hmaerki** [comment] 2024-09-07 15:10
@mattytrentini: Thanks a lot for the precise answer! I could build the images.

It looks like that RPI_PICO, variant RISCV is not supported yet.

This PR https://github.com/mattytrentini/build-micropython-arm-docker/pull/1 is a docker image which supports to build RPI_PICO, variant RISCV.

**Comment by mattytrentini** [comment] 2024-11-19 00:13
Thanks to @hmaerki's contribution to supply a [build container definition for the RISC-V variant of the RP2350](https://github.com/mattytrentini/build-micropython-rp2350riscv-docker) (published at [micropython-rp2350riscv](https://hub.docker.com/r/micropython/build-micropython-rp2350riscv)), it can now be built like so:

```bash
mpbuild build --build-container micropython/build-micropython-rp2350riscv RPI_PICO2 RISCV
```

Currently the build container needs to be overridden because mpbuild only selects containers based on the port the board belongs to - which is incorrect for the RISC-V variant (it'll use [micropython/micropython-build-arm](https://hub.docker.com/r/micropython/build-micropython-arm)). The intent is to resolve that with #35 to allow more fine-grained mapping between boards and build containers. 

However, we can now build for the RP2350/RISCV and so I'll close this ticket. Thanks @hmaerki!

**Closed by mattytrentini** 2024-11-19 00:13 UTC
